import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Notable } from 'next/font/google'

import './globals.css'
import Link from "next/link"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <nav className='flex justify-between p-14'>   {/* justify-center */}
        <div> <Link href="/logo"> The shop </Link></div> {/* */}
        <ul className="flex text-lg gap-4">
        <li>
            <Link href="/">Home</Link>
          </li>
         
          <li>
            <Link href="/about">About111</Link>
          </li>
          <li>
            <Link href="/products">Products</Link>
          </li>
          <li>
            <Link href="/contact">Contact88888888</Link>
          </li>         
          <li>
            <Link href="/sign_in">Sign_in</Link>
          </li>
          <li>
            <Link href="/likes">Likes</Link>
          </li>          
          <li>
            <Link href="/cart">Cart</Link>
          </li>
        </ul>
      </nav>
        {children}
      </body>
      
    </html>
  )
}
